/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actor_id: string | null;
  after: Json | null;
  before: Json | null;
  created_at: Generated<Timestamp>;
  entity: string;
  entity_id: string | null;
  id: Generated<Int8>;
  ip: string | null;
  tenant_id: string;
}

export interface Booking {
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  checkin_at: Timestamp | null;
  checkin_by: string | null;
  checkin_method: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deducted: Generated<boolean>;
  ends_at: Timestamp;
  id: Generated<string>;
  member_id: string;
  member_package_id: string;
  note: string | null;
  starts_at: Timestamp;
  status: Generated<string>;
  tenant_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Campaign {
  channel: string;
  code: string;
  cooldown_days: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  template_code: string;
  tenant_id: string;
  threshold: number;
  trigger_type: string;
  updated_at: Generated<Timestamp>;
}

export interface CampaignEnrollment {
  campaign_id: string;
  member_package_id: string;
  outbox_id: Int8 | null;
  tenant_id: string;
  triggered_at: Generated<Timestamp>;
}

export interface CheckinToken {
  booking_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  tenant_id: string;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface CommissionEntry {
  amount: Int8;
  base_amount: Int8;
  booking_id: string | null;
  earned_at: Generated<Timestamp>;
  id: Generated<Int8>;
  kind: string;
  member_package_id: string;
  paid_out_at: Timestamp | null;
  payment_id: string | null;
  period_month: Timestamp;
  policy_snapshot: Json;
  tenant_id: string;
  trainer_id: string;
}

export interface CommissionPolicy {
  created_at: Generated<Timestamp>;
  effective_from: Timestamp;
  effective_to: Timestamp | null;
  id: Generated<string>;
  package_template_id: string | null;
  sale_pct: Generated<Numeric>;
  teach_fixed_amount: Generated<Int8>;
  teach_mode: Generated<string>;
  teach_pct: Generated<Numeric>;
  tenant_id: string;
  trainer_id: string | null;
}

export interface FileObject {
  bucket: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mime: string;
  object_key: string;
  owner_id: string | null;
  owner_type: string;
  size_bytes: Int8;
  tenant_id: string;
  uploaded_by: string | null;
}

export interface Identity {
  created_at: Generated<Timestamp>;
  email: string | null;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  password_hash: string | null;
  phone: string;
  phone_verified_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface IdentityPhoneHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  id: Generated<Int8>;
  identity_id: string;
  new_phone: string;
  old_phone: string;
}

export interface Invoice {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_installment: Generated<boolean>;
  issued_at: Generated<Timestamp>;
  member_id: string;
  note: string | null;
  paid_amount: Generated<Int8>;
  pdf_file_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  total_amount: Int8;
  updated_at: Generated<Timestamp>;
  voided_at: Timestamp | null;
  voided_by: string | null;
}

export interface InvoiceItem {
  amount: Int8;
  description: string;
  id: Generated<string>;
  invoice_id: string;
  member_package_id: string | null;
  quantity: Generated<number>;
  tenant_id: string;
  unit_price: Int8;
}

export interface Member {
  avatar_key: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  dob: Timestamp | null;
  gender: string | null;
  id: Generated<string>;
  identity_id: string;
  note: string | null;
  referred_by: string | null;
  source: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  zalo_user_id: string | null;
}

export interface MemberPackage {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  discount: Generated<Int8>;
  expires_on: Timestamp;
  frozen_days: Generated<number>;
  id: Generated<string>;
  member_id: string;
  name_snapshot: string;
  price_gross: Int8;
  price_net: Generated<Int8 | null>;
  sessions_total: number;
  sessions_used: Generated<number>;
  sold_by_id: string | null;
  starts_on: Timestamp;
  status: Generated<string>;
  template_id: string;
  tenant_id: string;
  trainer_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface NotificationOutbox {
  attempts: Generated<number>;
  channel: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  idempotency_key: string;
  last_error: string | null;
  member_id: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Generated<Json>;
  provider_msg_id: string | null;
  recipient_ref: string;
  sent_at: Timestamp | null;
  status: Generated<string>;
  template_code: string;
  tenant_id: string;
}

export interface OtpChallenge {
  attempts: Generated<number>;
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  phone: string;
  purpose: string;
}

export interface PackageFreeze {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  frozen_from: Timestamp;
  frozen_to: Timestamp | null;
  id: Generated<string>;
  member_package_id: string;
  reason: string | null;
  tenant_id: string;
}

export interface PackageTemplate {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: string;
  late_cancel_deducts: boolean | null;
  late_cancel_hours: number | null;
  name: string;
  no_show_deducts: boolean | null;
  price: Int8;
  sessions: number;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  valid_days: number;
}

export interface Payment {
  amount: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  invoice_id: string;
  kind: Generated<string>;
  method: string;
  note: string | null;
  paid_at: Generated<Timestamp>;
  received_by: string | null;
  reference: string | null;
  schedule_id: string | null;
  signed_amount: Generated<Int8 | null>;
  tenant_id: string;
}

export interface PaymentSchedule {
  amount: Int8;
  due_date: Timestamp;
  id: Generated<string>;
  invoice_id: string;
  seq: number;
  status: Generated<string>;
  tenant_id: string;
}

export interface Plan {
  code: string;
  features: Generated<Json>;
  is_public: Generated<boolean>;
  max_members: number | null;
  max_messages_month: number | null;
  max_trainers: number | null;
  name: string;
  price_monthly: Int8;
  sort_order: Generated<number>;
}

export interface PlatformAdmin {
  created_at: Generated<Timestamp>;
  identity_id: string;
  level: Generated<string>;
}

export interface PlatformAuditLog {
  action: string;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  detail: Generated<Json>;
  id: Generated<Int8>;
  ip: string | null;
  target_tenant: string | null;
}

export interface RefreshToken {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  identity_id: string;
  ip: string | null;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  tenant_id: string | null;
  token_hash: string;
  user_agent: string | null;
}

export interface RevenueEntry {
  amount: Int8;
  booking_id: string;
  id: Generated<Int8>;
  member_package_id: string;
  recognized_at: Generated<Timestamp>;
  tenant_id: string;
  trainer_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  duration_ms: number;
  name: string;
  version: string;
}

export interface SessionLedger {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  delta: number;
  id: Generated<Int8>;
  member_package_id: string;
  note: string | null;
  reason: string;
  ref_id: string | null;
  ref_type: string | null;
  tenant_id: string;
}

export interface Tenant {
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<string>;
  logo_key: string | null;
  name: string;
  slug: string;
  status: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TenantBillingRecord {
  amount: Int8;
  confirmed_at: Timestamp | null;
  confirmed_by: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  period_end: Timestamp;
  period_start: Timestamp;
  plan_code: string;
  status: Generated<string>;
  tenant_id: string;
  transfer_ref: string | null;
}

export interface TenantMessageUsage {
  channel: string;
  period_month: Timestamp;
  sent_count: Generated<number>;
  tenant_id: string;
}

export interface TenantPolicy {
  booking_window_days: Generated<number>;
  checkin_grace_minutes: Generated<number>;
  late_cancel_deducts: Generated<boolean>;
  late_cancel_hours: Generated<number>;
  no_show_deducts: Generated<boolean>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantSubscription {
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  plan_code: string;
  status: Generated<string>;
  tenant_id: string;
  trial_ends_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantUser {
  identity_id: string;
  joined_at: Generated<Timestamp>;
  role: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface TenantZaloOa {
  access_token_enc: Buffer | null;
  app_id: string;
  connected_at: Timestamp | null;
  last_error: string | null;
  oa_id: string;
  refresh_token_enc: Buffer | null;
  secret_enc: Buffer;
  status: Generated<string>;
  tenant_id: string;
  token_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantZnsTemplate {
  provider_tpl_id: string | null;
  reject_reason: string | null;
  status: Generated<string>;
  template_code: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Trainer {
  avatar_key: string | null;
  base_salary: Generated<Int8>;
  bio: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  hired_on: Timestamp | null;
  id: Generated<string>;
  identity_id: string;
  left_on: Timestamp | null;
  level: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TrainerAvailability {
  end_time: string;
  id: Generated<string>;
  start_time: string;
  tenant_id: string;
  trainer_id: string;
  weekday: number;
}

export interface VInvoicePaidDrift {
  cached_paid: Int8 | null;
  code: string | null;
  drift: Numeric | null;
  invoice_id: string | null;
  ledger_paid: Numeric | null;
  tenant_id: string | null;
}

export interface VSessionBalanceDrift {
  cached_used: number | null;
  code: string | null;
  drift: Int8 | null;
  ledger_used: Int8 | null;
  member_package_id: string | null;
  sessions_total: number | null;
  tenant_id: string | null;
}

export interface DB {
  audit_log: AuditLog;
  booking: Booking;
  campaign: Campaign;
  campaign_enrollment: CampaignEnrollment;
  checkin_token: CheckinToken;
  commission_entry: CommissionEntry;
  commission_policy: CommissionPolicy;
  file_object: FileObject;
  identity: Identity;
  identity_phone_history: IdentityPhoneHistory;
  invoice: Invoice;
  invoice_item: InvoiceItem;
  member: Member;
  member_package: MemberPackage;
  notification_outbox: NotificationOutbox;
  otp_challenge: OtpChallenge;
  package_freeze: PackageFreeze;
  package_template: PackageTemplate;
  payment: Payment;
  payment_schedule: PaymentSchedule;
  plan: Plan;
  platform_admin: PlatformAdmin;
  platform_audit_log: PlatformAuditLog;
  refresh_token: RefreshToken;
  revenue_entry: RevenueEntry;
  schema_migrations: SchemaMigrations;
  session_ledger: SessionLedger;
  tenant: Tenant;
  tenant_billing_record: TenantBillingRecord;
  tenant_message_usage: TenantMessageUsage;
  tenant_policy: TenantPolicy;
  tenant_subscription: TenantSubscription;
  tenant_user: TenantUser;
  tenant_zalo_oa: TenantZaloOa;
  tenant_zns_template: TenantZnsTemplate;
  trainer: Trainer;
  trainer_availability: TrainerAvailability;
  v_invoice_paid_drift: VInvoicePaidDrift;
  v_session_balance_drift: VSessionBalanceDrift;
}
