/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

/**
 * Cột `date` của Postgres: một ngày trên tờ lịch, KHÔNG phải một thời điểm.
 * Ứng dụng đặt setTypeParser để nó giữ nguyên chuỗi 'YYYY-MM-DD' — đừng gọi
 * `new Date(...)` lên nó rồi `.toISOString()`, sẽ lùi một ngày ở múi giờ +07.
 */
export type DateString = ColumnType<string, string, string>;

export interface AuditLog {
  action: string;
  actor_id: string | null;
  after: Json | null;
  before: Json | null;
  created_at: Generated<Timestamp>;
  entity: string;
  entity_id: string | null;
  id: Generated<Int8>;
  ip: string | null;
  tenant_id: string;
}

export interface BankTxnEvent {
  account_no: string | null;
  amount: Int8;
  bank_ref: string | null;
  content: Generated<string>;
  direction: string;
  id: Generated<Int8>;
  invoice_id: string | null;
  matched_tenant: string | null;
  outcome: string;
  payload: Json;
  provider: string;
  provider_txn_id: string;
  received_at: Generated<Timestamp>;
  resolve_note: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  txn_at: Timestamp | null;
}

export interface Booking {
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  checkin_at: Timestamp | null;
  checkin_by: string | null;
  checkin_method: string | null;
  checkin_note: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deducted: Generated<boolean>;
  ends_at: Timestamp;
  id: Generated<string>;
  member_id: string;
  member_package_id: string;
  note: string | null;
  starts_at: Timestamp;
  status: Generated<string>;
  tenant_id: string;
  trainer_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Campaign {
  channel: string;
  code: string;
  cooldown_days: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  template_code: string;
  tenant_id: string;
  threshold: number;
  trigger_type: string;
  updated_at: Generated<Timestamp>;
}

export interface CampaignEnrollment {
  campaign_id: string;
  member_package_id: string;
  outbox_id: Int8 | null;
  tenant_id: string;
  triggered_at: Generated<Timestamp>;
}

export interface CheckinToken {
  booking_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  tenant_id: string;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface CommissionEntry {
  /**
   * VND. ÂM = bút toán đảo khi hoàn tiền. Không bao giờ sửa dòng cũ.
   */
  amount: Int8;
  base_amount: Int8;
  booking_id: string | null;
  earned_at: Generated<Timestamp>;
  id: Generated<Int8>;
  kind: string;
  member_package_id: string;
  paid_out_at: Timestamp | null;
  payment_id: string | null;
  payroll_line_id: string | null;
  period_month: DateString;
  policy_snapshot: Json;
  tenant_id: string;
  trainer_id: string;
}

export interface CommissionPolicy {
  created_at: Generated<Timestamp>;
  effective_from: DateString;
  effective_to: DateString | null;
  id: Generated<string>;
  package_template_id: string | null;
  sale_pct: Generated<Numeric>;
  teach_fixed_amount: Generated<Int8>;
  teach_mode: Generated<string>;
  teach_pct: Generated<Numeric>;
  tenant_id: string;
  trainer_id: string | null;
}

export interface FileObject {
  bucket: string;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mime: string;
  object_key: string;
  owner_id: string | null;
  owner_type: string;
  size_bytes: Int8 | null;
  status: Generated<string>;
  tenant_id: string;
  uploaded_by: string | null;
}

export interface Identity {
  created_at: Generated<Timestamp>;
  email: string | null;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  must_change_password: Generated<boolean>;
  password_hash: string | null;
  phone: string;
  phone_verified_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface IdentityPhoneHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  id: Generated<Int8>;
  identity_id: string;
  new_phone: string;
  old_phone: string;
}

export interface Invoice {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_installment: Generated<boolean>;
  issued_at: Generated<Timestamp>;
  member_id: string;
  note: string | null;
  paid_amount: Generated<Int8>;
  pdf_file_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  total_amount: Int8;
  updated_at: Generated<Timestamp>;
  voided_at: Timestamp | null;
  voided_by: string | null;
}

export interface InvoiceItem {
  amount: Int8;
  description: string;
  id: Generated<string>;
  invoice_id: string;
  member_package_id: string | null;
  quantity: Generated<number>;
  tenant_id: string;
  unit_price: Int8;
}

export interface Member {
  avatar_key: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  dob: DateString | null;
  gender: string | null;
  id: Generated<string>;
  identity_id: string;
  note: string | null;
  referred_by: string | null;
  source: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  zalo_user_id: string | null;
}

export interface MemberPackage {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  discount: Generated<Int8>;
  expires_on: DateString;
  frozen_days: Generated<number>;
  id: Generated<string>;
  member_id: string;
  name_snapshot: string;
  price_gross: Int8;
  price_net: Generated<Int8 | null>;
  /**
   * Tổng buổi được TẶNG = SUM(session_ledger.delta) với reason BONUS. Do trigger giữ, đừng ghi tay.
   */
  sessions_bonus: Generated<number>;
  /**
   * SỐ DƯ buổi tập = SUM(session_ledger.delta). Do trigger giữ, đừng ghi tay.
   */
  sessions_remaining: Generated<number>;
  sessions_total: number;
  /**
   * Số buổi ĐÃ TIÊU THỤ (điểm danh/vắng). KHÁC với sessions_total - sessions_remaining
   *    khi hợp đồng bị huỷ hoặc được tặng thêm buổi.
   */
  sessions_used: Generated<number>;
  sold_by_id: string | null;
  starts_on: DateString;
  status: Generated<string>;
  template_id: string;
  tenant_id: string;
  trainer_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface MemberProgress {
  body_fat_pm: number | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  member_id: string;
  muscle_hg: number | null;
  note: string | null;
  photo_file_id: string | null;
  recorded_on: DateString;
  tenant_id: string;
  weight_hg: number | null;
}

export interface NotificationOutbox {
  attempts: Generated<number>;
  channel: string;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  id: Generated<Int8>;
  idempotency_key: string;
  last_error: string | null;
  member_id: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Generated<Json>;
  provider_msg_id: string | null;
  recipient_ref: string;
  sent_at: Timestamp | null;
  status: Generated<string>;
  template_code: string;
  tenant_id: string;
}

export interface OtpChallenge {
  attempts: Generated<number>;
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  phone: string;
  purpose: string;
}

export interface PackageFreeze {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  frozen_from: DateString;
  frozen_to: DateString | null;
  id: Generated<string>;
  member_package_id: string;
  reason: string | null;
  tenant_id: string;
}

export interface PackageTemplate {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: string;
  late_cancel_deducts: boolean | null;
  late_cancel_hours: number | null;
  name: string;
  no_show_deducts: boolean | null;
  price: Int8;
  sessions: number;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  valid_days: number;
}

export interface Payment {
  amount: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string | null;
  invoice_id: string;
  kind: Generated<string>;
  method: string;
  note: string | null;
  paid_at: Generated<Timestamp>;
  received_by: string | null;
  reference: string | null;
  schedule_id: string | null;
  signed_amount: Generated<Int8 | null>;
  tenant_id: string;
}

export interface PaymentSchedule {
  amount: Int8;
  due_date: DateString;
  id: Generated<string>;
  invoice_id: string;
  seq: number;
  status: Generated<string>;
  tenant_id: string;
}

export interface PayrollLine {
  adjustment: Generated<Int8>;
  adjustment_note: string | null;
  base_salary: Int8;
  commission_sale: Generated<Int8>;
  commission_teach: Generated<Int8>;
  id: Generated<string>;
  run_id: string;
  sessions_taught: Generated<number>;
  tenant_id: string;
  total: Generated<Int8 | null>;
  trainer_id: string;
}

export interface PayrollRun {
  closed_at: Timestamp | null;
  closed_by: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  paid_at: Timestamp | null;
  paid_by: string | null;
  period_month: DateString;
  status: Generated<string>;
  tenant_id: string;
}

export interface Plan {
  code: string;
  features: Generated<Json>;
  is_public: Generated<boolean>;
  max_members: number | null;
  max_messages_month: number | null;
  max_trainers: number | null;
  name: string;
  price_monthly: Int8;
  sort_order: Generated<number>;
}

export interface PlanChangeRequest {
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  from_plan: string;
  id: Generated<string>;
  note: string | null;
  requested_by: string;
  status: Generated<string>;
  tenant_id: string;
  to_plan: string;
}

export interface PlatformAdmin {
  created_at: Generated<Timestamp>;
  identity_id: string;
  level: Generated<string>;
}

export interface PlatformAuditLog {
  action: string;
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  detail: Generated<Json>;
  id: Generated<Int8>;
  ip: string | null;
  target_tenant: string | null;
}

export interface ReconciliationRun {
  counts: Json;
  duration_ms: Generated<number>;
  errors: Generated<Json>;
  id: Generated<Int8>;
  ran_at: Generated<Timestamp>;
  samples: Generated<Json>;
  total: number;
}

export interface RefreshToken {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  identity_id: string;
  ip: string | null;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  tenant_id: string | null;
  token_hash: string;
  user_agent: string | null;
}

export interface ReportingRefreshLog {
  duration_ms: number;
  id: Generated<Int8>;
  refreshed_at: Generated<Timestamp>;
}

export interface RevenueEntry {
  amount: Int8;
  booking_id: string;
  id: Generated<Int8>;
  member_package_id: string;
  recognized_at: Generated<Timestamp>;
  source: Generated<string>;
  tenant_id: string;
  trainer_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  duration_ms: number;
  name: string;
  version: string;
}

export interface SessionLedger {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  delta: number;
  id: Generated<Int8>;
  member_package_id: string;
  note: string | null;
  reason: string;
  ref_id: string | null;
  ref_type: string | null;
  tenant_id: string;
}

export interface StaffNotification {
  body: string;
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  dedupe_key: string;
  id: Generated<string>;
  identity_id: string;
  kind: string;
  link: string | null;
  read_at: Timestamp | null;
  tenant_id: string;
  title: string;
}

export interface Tenant {
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<string>;
  logo_key: string | null;
  name: string;
  slug: string;
  status: Generated<string>;
  status_note: string | null;
  suspend_kind: string | null;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TenantBillingRecord {
  amount: Int8;
  bank_event_id: Int8 | null;
  bank_txn_ref: string | null;
  confirmed_at: Timestamp | null;
  confirmed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  due_date: DateString;
  id: Generated<string>;
  note: string | null;
  paid_amount: Int8 | null;
  period_end: DateString;
  period_start: DateString;
  plan_code: string;
  status: Generated<string>;
  tenant_id: string;
  transfer_ref: string;
}

export interface TenantMessageUsage {
  channel: string;
  period_month: DateString;
  sent_count: Generated<number>;
  tenant_id: string;
}

export interface TenantPolicy {
  auto_no_show: Generated<boolean>;
  booking_window_days: Generated<number>;
  checkin_grace_minutes: Generated<number>;
  late_cancel_deducts: Generated<boolean>;
  late_cancel_hours: Generated<number>;
  no_show_deducts: Generated<boolean>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantSubscription {
  current_period_end: DateString;
  current_period_start: DateString;
  plan_code: string;
  status: Generated<string>;
  tenant_id: string;
  trial_ends_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantTerms {
  content: string;
  id: Generated<string>;
  published_at: Generated<Timestamp>;
  published_by: string;
  tenant_id: string;
  version: number;
}

export interface TenantUser {
  identity_id: string;
  joined_at: Generated<Timestamp>;
  role: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface TenantZaloOa {
  access_token_enc: Buffer | null;
  app_id: string;
  connected_at: Timestamp | null;
  last_error: string | null;
  oa_id: string | null;
  refresh_token_enc: Buffer | null;
  secret_enc: Buffer;
  status: Generated<string>;
  tenant_id: string;
  token_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  webhook_secret_enc: Buffer | null;
}

export interface TenantZnsTemplate {
  provider_tpl_id: string | null;
  reject_reason: string | null;
  status: Generated<string>;
  template_code: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Trainer {
  avatar_key: string | null;
  base_salary: Generated<Int8>;
  bio: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  hired_on: DateString | null;
  id: Generated<string>;
  identity_id: string;
  left_on: DateString | null;
  level: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TrainerAvailability {
  end_time: string;
  id: Generated<string>;
  start_time: string;
  tenant_id: string;
  trainer_id: string;
  weekday: number;
}

export interface VCommissionNeedsPolicy {
  base_amount: Int8 | null;
  commission_entry_id: Int8 | null;
  earned_at: Timestamp | null;
  payment_id: string | null;
  resolved_on: string | null;
  tenant_id: string | null;
  trainer_id: string | null;
}

export interface VInvoicePaidDrift {
  cached_paid: Int8 | null;
  code: string | null;
  drift: Numeric | null;
  invoice_id: string | null;
  ledger_paid: Numeric | null;
  tenant_id: string | null;
}

export interface VPackageMonth {
  discount_amount: Int8 | null;
  gross_amount: Int8 | null;
  net_amount: Int8 | null;
  period_month: DateString | null;
  sessions_sold: number | null;
  sessions_used: number | null;
  sold_count: number | null;
  template_id: string | null;
  tenant_id: string | null;
}

export interface VPayrollDrift {
  chot_ban: Int8 | null;
  chot_day: Int8 | null;
  payroll_line_id: string | null;
  run_id: string | null;
  tenant_id: string | null;
  thuc_ban: Numeric | null;
  thuc_day: Numeric | null;
  trainer_id: string | null;
}

export interface VRevenueDrift {
  booking_id: string | null;
  deducted: boolean | null;
  so_dong_doanh_thu: Int8 | null;
  status: string | null;
  tenant_id: string | null;
}

export interface VRevenueOverContract {
  code: string | null;
  da_ghi_nhan: Numeric | null;
  member_package_id: string | null;
  price_net: Int8 | null;
  tenant_id: string | null;
}

export interface VSaleCommissionDrift {
  invoice_id: string | null;
  payment_id: string | null;
  signed_amount: Int8 | null;
  so_dong_hoa_hong: Int8 | null;
  sold_by_id: string | null;
  tenant_id: string | null;
}

export interface VSessionBalanceDrift {
  cached_remaining: number | null;
  cached_used: number | null;
  code: string | null;
  ledger_remaining: Int8 | null;
  ledger_used: Int8 | null;
  member_package_id: string | null;
  sessions_total: number | null;
  tenant_id: string | null;
}

export interface VTeachCommissionDrift {
  booking_id: string | null;
  doanh_thu: Int8 | null;
  so_dong_hoa_hong: Int8 | null;
  tenant_id: string | null;
  trainer_id: string | null;
}

export interface VTenantMonth {
  cash_in: Int8 | null;
  cash_out: Int8 | null;
  gross_sales: Int8 | null;
  new_members: number | null;
  packages_sold: number | null;
  period_month: DateString | null;
  revenue_recognized: Int8 | null;
  sessions_deducted: number | null;
  sessions_taught: number | null;
  tenant_id: string | null;
}

export interface VTrainerMonth {
  commission_sale: Int8 | null;
  commission_teach: Int8 | null;
  period_month: DateString | null;
  revenue_recognized: Int8 | null;
  sessions_deducted: number | null;
  sessions_taught: number | null;
  tenant_id: string | null;
  trainer_id: string | null;
}

export interface DB {
  audit_log: AuditLog;
  bank_txn_event: BankTxnEvent;
  booking: Booking;
  campaign: Campaign;
  campaign_enrollment: CampaignEnrollment;
  checkin_token: CheckinToken;
  commission_entry: CommissionEntry;
  commission_policy: CommissionPolicy;
  file_object: FileObject;
  identity: Identity;
  identity_phone_history: IdentityPhoneHistory;
  invoice: Invoice;
  invoice_item: InvoiceItem;
  member: Member;
  member_package: MemberPackage;
  member_progress: MemberProgress;
  notification_outbox: NotificationOutbox;
  otp_challenge: OtpChallenge;
  package_freeze: PackageFreeze;
  package_template: PackageTemplate;
  payment: Payment;
  payment_schedule: PaymentSchedule;
  payroll_line: PayrollLine;
  payroll_run: PayrollRun;
  plan: Plan;
  plan_change_request: PlanChangeRequest;
  platform_admin: PlatformAdmin;
  platform_audit_log: PlatformAuditLog;
  reconciliation_run: ReconciliationRun;
  refresh_token: RefreshToken;
  reporting_refresh_log: ReportingRefreshLog;
  revenue_entry: RevenueEntry;
  schema_migrations: SchemaMigrations;
  session_ledger: SessionLedger;
  staff_notification: StaffNotification;
  tenant: Tenant;
  tenant_billing_record: TenantBillingRecord;
  tenant_message_usage: TenantMessageUsage;
  tenant_policy: TenantPolicy;
  tenant_subscription: TenantSubscription;
  tenant_terms: TenantTerms;
  tenant_user: TenantUser;
  tenant_zalo_oa: TenantZaloOa;
  tenant_zns_template: TenantZnsTemplate;
  trainer: Trainer;
  trainer_availability: TrainerAvailability;
  v_commission_needs_policy: VCommissionNeedsPolicy;
  v_invoice_paid_drift: VInvoicePaidDrift;
  v_package_month: VPackageMonth;
  v_payroll_drift: VPayrollDrift;
  v_revenue_drift: VRevenueDrift;
  v_revenue_over_contract: VRevenueOverContract;
  v_sale_commission_drift: VSaleCommissionDrift;
  v_session_balance_drift: VSessionBalanceDrift;
  v_teach_commission_drift: VTeachCommissionDrift;
  v_tenant_month: VTenantMonth;
  v_trainer_month: VTrainerMonth;
}
